name: Docker Image CI for GHCR Boxlang

on:
  push

jobs: 
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run: |
          docker login --username webmandman --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/webmandman/hello-world-ghcr:latest
          docker push ghcr.io/webmandman/hello-world-ghcr:latest

